export const searchTypes = [
    'bakery',
    'pharmacy',
    'store',
    'restaurant',
    'cafe',
    'bar',
    'museum',
    'night_club',
    'park',
    'bank',
    'school',
    'secondary_school',
    'airport',
    'landmark',
    'point_of_interest',
]
