export const TYPES = {
    BAKERY: 'bakery',
    PHARMACY: 'pharmacy',
    RESTAURANT: 'restaurant',
    STORE: 'store',
    CAFE: 'cafe',
    BAR: 'bar',
    MUSEUM: 'museum',
    NIGHT_CLUB: 'night_club',
    PARK: 'park',
    BANK: 'bank',
    SCHOOL: 'school',
    SECONDARY_SCHOOL: 'secondary_school',
    AIRPORT: 'airport',
    LANDMARK: 'landmark',
    POINT_OF_INTEREST: 'point_of_interest',
}
